### ISSUE TITLE
Conflicting with Bootstrap panels

### ISSUE THREAD

**Issue by ollie007** [quoid/panels#3]
Conflicting with Bootstrap panels, same namespace

How can i resolve this?

**Comment by quoid** [comment]
@ollie007 

What's the issue exactly? There's no documentation uploaded yet to the repo, so I'm wondering how you set everything up.

It's important to note that currently panels is in a preliminary development and `v0.2.0` won't be done for a few weeks. There's loads of bugs and optimization I am working out.

**Comment by ollie007** [comment]
Bootstrap panels
    < div class="panel panel-default">
      < div class="panel-body">
        Basic panel example
      < /div>
    < /div>

when I use bootstraps panel with their collapse component, your "panel" wont let it open, because it uses the same namespace

Maybe you should rename your class to "panels" plural

**Comment by quoid** [comment]
Is there a live server I can see this behavior?

The lack of documentation is going to make this set up a bit difficult as I can see here.

`<body>`
  `<div class="panel left">//content in panel</div>`
  `<div class="panel-wrapper">`
      `//site-content`
  `</div>`
`</body>`

Note: you can use `left`, `right`, `top` or `bottom` depending on where you want your panel - just make sure to include the `panel` class as well.

You will also need something called `left-panel-trigger` to open and close the panel. Again, swap _left_ for whatever panel origin you are using.

I'd suggested checking the repo again in a few weeks, when the project documentation is up along with the newer version and in the meantime look for a different panel library.

**Comment by ollie007** [comment]
"A pretended Law ......" is maximised  on load... I only inserted the js and css and bam, it is locked and I cannot show the bootstrap panel

**Comment by ollie007** [comment]
Btw, if you can tell me why the vimeo isnt responsive there on that page  BUT is responsive here:

i would be very grateful, i have been tearing my hair out

**Comment by ollie007** [comment]
BTW, i was hoping to use your work to push down the header image element, and enlarge it for display, exposing the full image area up top

**Comment by ollie007** [comment]
yeah so if you are in development, i would be grateful if you change the class to "PANELS" plural

**Comment by quoid** [comment]
I couldn't tell anything from the webpage, but it's likely due to incorrect class names, which is a result of there not being any documentation about the library.

Also, these issues will only be for the library in questions (_panels_).

> yeah so if you are in development, i would be grateful if you change the class to "PANELS" plural

A lot is changing in the next version, including class names; stay tuned!
- Closing this issue
